# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'genusbar_ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for genusbar_ios
  pod 'XLPagerTabStrip', '~> 8.1'

  target 'genusbar_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'genusbar_iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
